/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.hu.bjornchaudron;

import java.net.URL;
import java.net.URLEncoder;
import org.openide.awt.HtmlBrowser.URLDisplayer;

/**
 *
 * @author Bjorn
 */
public class OracleDocPanel extends javax.swing.JPanel {

    /**
     * Creates new form OracleDocPanel
     */
    public OracleDocPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBar = new javax.swing.JTextField();
        oracleLabel = new javax.swing.JLabel();

        searchBar.setText(org.openide.util.NbBundle.getMessage(OracleDocPanel.class, "OracleDocPanel.searchBar.text")); // NOI18N
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(oracleLabel, org.openide.util.NbBundle.getMessage(OracleDocPanel.class, "OracleDocPanel.oracleLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oracleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBar, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oracleLabel)
                    .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        try {
            String searchText = URLEncoder.encode(searchBar.getText(), "UTF-8");
            URLDisplayer.getDefault().showURL(new URL("https://search.oracle.com/search/search?search_p_main_operator=all&group=Documentation&q=" 
                    + searchText + "+url%3A%2Fjavase%2F8%2Fdocs%2Fapi&searchField="+ searchText + "&docsets=%2Fjavase%2F8%2Fdocs%2Fapi"));
        } catch (Exception eee) {
            return;//nothing much to do
        }
    }//GEN-LAST:event_searchBarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel oracleLabel;
    private javax.swing.JTextField searchBar;
    // End of variables declaration//GEN-END:variables
}
